### ISSUE TITLE
Limit number of decimals in legend

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-geo#1]
Values with unlimited number of decimals are unreadable.

<img width="268" alt="screen shot 2017-05-03 at 18 10 25" src="https://cloud.githubusercontent.com/assets/588601/25670083/dce08af0-302b-11e7-817c-ee03dda03b11.png">

**Comment by kernc** [comment]
Fixed in https://github.com/biolab/orange3-geo/commit/810d84116538433ebae3b9df8295df497be2ab2a
