### ISSUE TITLE
Choropleth widget missing

### ISSUE THREAD

**Issue by klonuo** [biolab/orange3-geo#11]
Hi,

I use latest Orange git version.

Reading recent blog post: https://blog.biolab.si/2017/08/28/can-we-download-orange-faster/ it seems like there should be choropleth widget, probably in geo addon (I have installed latest 1.8 version), but I don't have such widget.

Any ideas?

Thanks

**Comment by jerneju** [comment]
Some packages are probably missing. Be sure you have installed at least **Qt 5.3** and **shapely**.

**Comment by klonuo** [comment]
Here is my env:

```batch
(env) C:\Users\klo\Documents\Projects\orange3>pip freeze | findstr /i /r shapely
Shapely==1.5.17

(env) C:\Users\klo\Documents\Projects\orange3>pip freeze | findstr /i /r qt
AnyQt==0.0.8
PyQt4==4.11.4
pyqtgraph==0.10.0
qtconsole==4.3.1
```

**Comment by kernc** [comment]
You need PyQt5.
If you run orange with `python -m Orange.canvas -l 4`, the printed errors might shed some light upon the issue.

**Comment by klonuo** [comment]
Indeed. Thanks.

From the log: `RuntimeError: Choropleth widget only works with Qt 5.3+`

Using `pip install pyqt5` on Windows, surprisingly went w/o issue, and Choropleth widget shows as expected.

Cheers
