### ISSUE TITLE
Just loading one Widget - all other Geo-widgets missing

### ISSUE THREAD

**Issue by ghost** [biolab/orange3-geo#119]
##### Geo version
0.2.8

##### Orange version
3.27.1

##### Expected behavior

to see all Geo-Widgets

##### Actual behavior

to see all available Geo-Widgets

##### Steps to reproduce the behavior

I installed the new Geo Version and just the main Geo-Widget is available. I also tried to pip install, to load it from source... always same result

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/70333777/101625655-0312ef80-3a1c-11eb-8316-b5ba83a02a7b.png)

**Comment by kernc** [comment]
[Start Orange from the command line](https://github.com/biolab/orange3/tree/24378a50c5a1e76c0ac723ddd5a104994ec5b2ba#starting-orange-gui) and see what errors show up.

**Comment by hansdeheer** [comment]
Same behaviour here as @DS-in-Tourism experiences: only the Geo Map widget shows up. Running Orange 3.26 from Anaconda 202-11 on Windows 10. Tried running Orange from the commandline as suggested by @kernc , no errors but also no other widgets than Geo Map. Is there a list of requirements available for the Geo plugin to run succesfully (libraries + versions)?

**Comment by kernc** [comment]
I think you should run it with `-v` to increase verbosity: `python3 -m Orange.canvas -v` or something.

Obviously the package has its dependencies:
https://github.com/biolab/orange3-geo/blob/0c78d96894059b57fb9f231fd8769bae554b8a33/setup.py#L49-L57
These should have been installed when installing the addon, though.

**Comment by hansdeheer** [comment]
@kernc Thanks for your help. I just browsed the other issues that were logged here and found the solution for this problem here:

https://github.com/biolab/orange3-geo/issues/106

Running **conda install -c conda-forge geos** did the trick, as suggested in that issue.

**Comment by JakaKokosar** [comment]
I believe this to be fixed when we merge: https://github.com/biolab/orange-canvas-core/pull/166

In my limited testing, I found out that add-ons install via pip and not trough conda, which for some reason did not install all the necessary dependencies. @thocevar reported that he had no problem installing this add-on in a non-conda environment.

**Comment by irgolic** [comment]
If anyone else experiences this problem on Orange<=3.27, try installing the master branch of biolab/orange-canvas-core. If it doesn't help, please reopen the issue/open a new issue, and let us know.
