### ISSUE TITLE
Feature Request: Add shapley function to set CRS 

### ISSUE THREAD

**Issue by ThirstyGeo** [biolab/orange3-geo#127]
##### Geo version

0.3.0

##### Orange version

3.29

##### Expected behavior
Options to use a variety of Coordinate Reference Systems (CRS)

##### Actual behavior
CRS is locked to WGS84

##### Additional info (worksheets, data, screenshots, ...)
Shapely (used by Geo Map) has the capacity to load coordinate data in any CRS:

  `import pyproj`
  
  `from shapely.geometry import Point`
  `from shapely.ops import transform`
  
  `wgs84_pt = Point(-72.2495, 43.886)`
  
  `wgs84 = pyproj.CRS('EPSG:4326')`
  `utm = pyproj.CRS('EPSG:32618')`
  
  `project = pyproj.Transformer.from_crs(wgs84, utm, always_xy=True).transform`
  `utm_point = transform(project, wgs84_pt)`

**Comment by ajdapretnar** [comment]
Would #130 solve the problem? Instead of converting on the fly, the widget adds converted lat/lot to the data table.

**Comment by ThirstyGeo** [comment]
Actually yes! That would be quite a useful widget, for all those of us working in the geospatial world

**Comment by ajdapretnar** [comment]
The widget is now merged and will be included in the new release.
