### ISSUE TITLE
Geocoding layout when no issues

### ISSUE THREAD

**Issue by janezd** [biolab/orange3-geo#135]
**Geo version**: 0.3.0
**Orange version**: 3.30.1

When there are no issues, the widget should either resize, show an empty list of issues or at least use rubber. Currently it looks like this. 

<img width="960" alt="Screenshot 2021-10-14 at 11 36 53" src="https://user-images.githubusercontent.com/2387315/137293511-b7b17bd7-824e-47b4-a9fb-29d47825ba9a.png">

**Comment by ajdapretnar** [comment]
Possibly @ales-erjavec could do this quickly and elegantly?
