### ISSUE TITLE
Zoomin in Geo Map

### ISSUE THREAD

**Issue by janezd** [biolab/orange3-geo#140]
#143 fixes trackpad zooming, so this is now less urgent, yet it would be nice to have -- if anybody knows what to do to have key events in the graph. :)

Close #116.

##### Expected behavior

I would suggest adding the following methods:
- [] Cmd-0 zooms to initial zoom
- [] double click at some point zooms in, centered to that point

##### Geo version

0.3.0

**Comment by ajdapretnar** [comment]
This should probably be a discussion under #116.

**Comment by janezd** [comment]
Thanks. I added closes #116 to this PR description.
