### ISSUE TITLE
GeoTransform: a few improvements

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#144]
Add a few improvement to the new GeoTransform:

- [x] Include report
- [x] Name new coordinates Lat and Lon if *Replace original coordinates* is unchecked.
- [x] Follow the logic for setting variables suggested in https://github.com/biolab/orange3-geo/pull/130#discussion_r799273612
- [x] If no data on input, don't display the "no lat/lon" error message.

**Comment by janezd** [comment]
> Name new coordinates Lat and Lon if Replace original coordinates is unchecked.

Using the same name was intentional. If original names were `širina` and `višina`, I'd like the new names to be `širina (1)` and `višina (1)`. It's easier to find and works better if data is not in English. Plus, I prefer latitude/longitude over lat/lon. :)

**Comment by ajdapretnar** [comment]
The point is Geo Map and Choropleth both find variables with "lat"/"lon" in names automatically in `find_lat_lon`, making the workflow super nice and easy. Otherwise, one has to manually set these variables. They can be called `latitude` and `longitude`, not problem, `find_lat_lon` can handle this.
