### ISSUE TITLE
Orange3 Geo cannot load OpenStreetMap

### ISSUE THREAD

**Issue by stenerikbjorling** [biolab/orange3-geo#150]
##### Geo version

0.3.0

##### Orange version

3.32

##### Expected behavior

Loading and presenting the OpenStreetMap when presenting data

##### Actual behavior

No OpenStreetMap is loaded - using non-exisiting cached files in my case. Can access and use OpenStreetMap at their website.

##### Steps to reproduce the behavior

Use the data set for illegal dump sites

**Comment by janezd** [comment]
Works for me and for some others who tried, too. Can you try again? Perhaps it was something on OSM's side.
