### ISSUE TITLE
Geocoding hangs in Windows and Linux

### ISSUE THREAD

**Issue by kaimikael** [biolab/orange3-geo#156]
##### Geo version

0.3.2

##### Orange version

3.34.0

##### Expected behavior
I expected Geocoding to create geocoded data from the dataset with country names I have.

##### Actual behavior
Orange (Python) hangs.  0% CPU, Task Manager says “Not responding”.
I kill the task and reopen Orange, it asks me if I want to restore the previous session.  If I do so, it hangs again.  (So no workflow attached.)

##### Steps to reproduce the behavior
On a Windows machine: Add a file widget, open a file with countries (see attached file), add a Geocoding widget, connect the two.  The connector turns red in both ends, indicating data is transferred, but then nothing else happens.

On a Linux machine: Do as above, and it hangs too.

On macOS all works fine.

##### Additional info (worksheets, data, screenshots, ...)
[hapiscore_whr.xlsx](https://github.com/biolab/orange3-geo/files/10217932/hapiscore_whr.xlsx)

These are the error messages I got from the Linux version:
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
libEGL warning: pci id for fd 18: 1ab8:0010, driver (null)

pci id for fd 19: 1ab8:0010, driver (null)
/usr/local/lib/python3.10/dist-packages/orangecontrib/timeseries/widgets/_owmodel.py:17: UserWarning: register 'summarize' function for type _BaseModel. To silence this warning, set auto_summary of 'Time series model' to False.
  class Outputs:
/usr/local/lib/python3.10/dist-packages/orangecontrib/timeseries/widgets/owarimamodel.py:8: RuntimeWarning: subclassing of widget classes is deprecated and will be disabled in the future.
Extract code from OWBaseModel or explicitly open it by adding `openclass=True` to class definition.
  class OWARIMAModel(OWBaseModel):
/usr/local/lib/python3.10/dist-packages/orangecontrib/timeseries/widgets/owmodelevaluation.py:36: UserWarning: register 'summarize' function for type _BaseModel. To silence this warning, set auto_summary of 'Time series model' to False.
  class Inputs:
/usr/local/lib/python3.10/dist-packages/orangecontrib/timeseries/widgets/owvarmodel.py:8: RuntimeWarning: subclassing of widget classes is deprecated and will be disabled in the future.
Extract code from OWBaseModel or explicitly open it by adding `openclass=True` to class definition.
  class OWVARModel(OWBaseModel):
<string>:4: DeprecationWarning: This function has no longer any effect, and will be removed in a future release. Starting with Shapely 2.0, equivalent speedups are always available
Exception in thread Thread-1 (init):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/orangecontrib/geo/mapper.py", line 131, in init
    for poly in polygons:
TypeError: 'MultiPolygon' object is not iterable
qt.qpa.wayland: Wayland does not support QWindow::requestActivate()
/usr/local/lib/python3.10/dist-packages/orangewidget/gui.py:2069: UserWarning: decorate OWGeocoding.commit with @gui.deferred and then explicitly call commit.now or commit.deferred.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/orangecontrib/geo/widgets/owgeocoding.py:289: OrangeDeprecationWarning: Call to deprecated <function Table.get_column_view at 0x7f2dc4e8f520>; Instead, use Table.get_column (or Table.set_column if you must)
  values = self.data.get_column_view(self.str_attr)[0]
Killed

**Comment by limves** [comment]
Same error in macOS ventura 13.1 + Orange 3.34.0 + Geo 0.3.2

**Comment by baozidai** [comment]
Same error in Windows10 + Orange 3.34.1 + Geo 0.3.2, both via installer and portable version

**Comment by ales-erjavec** [comment]
Until a new release, you will have to downgrade *shapely* package to 1.8 series.

On windows (via the installer) open Orange Command Prompt (from the start menu or Orange install folder) and run 

`conda install shapely=1.8 `

On macOS open Terminal.app and run 

`/Applications/Orange3.app/Contents/MacOS/pip install shapely~=1.8`
