### ISSUE TITLE
Choropleth and Geocoding function cause crashes - Windows 11

### ISSUE THREAD

**Issue by zokni41** [biolab/orange3-geo#165]
##### Expected behavior
Choropleth and Geocoding function.

##### Actual behavior
Use of Choropleth and Geocoding, even on test datasets such as HDI crash the program. 

I have tried an older version of orange [Orange3-3.31.0-Python38-win_amd64 exe](https://download.biolab.si/download/files/Orange3-3.31.0-Python38-win_amd64 exe)

And both Choropleth and Geocoding work fine. I updated again to 3.34 and I'm getting the same freezes/crashes.

<img width="1280" alt="Geocoding After - HDI" src="https://user-images.githubusercontent.com/124334272/216518065-1f7532aa-b38f-4e38-af94-33f9e8aceea8.png">
<img width="1280" alt="Geocoding before - HDI" src="https://user-images.githubusercontent.com/124334272/216518072-2843d8c0-98d9-4d2c-9b05-f4f6db4bf475.png">

##### Steps to reproduce the behavior
Load datasets widget
Select HDI
Connect Geocoding widget to HDI
- Crash

Or use an already geocoded dataset with latitude and longitude and connect it to the Choropleth map. Crash. 
The Geo Map function works ok but is a bit choppy/slow (no major complaints).

##### Additional info (worksheets, data, screenshots, ...)

PC specs.
Windows 11 Pro version 22H2
AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
16.0 GB (15.2 GB usable)
64-bit operating system, x64-based processor

**Comment by zokni41** [comment]
I put the data table widget in to the example screenshot and I'm aware that the output is 'selected data' - I get the same result whether I'm using a data table or not, I was just using  the data table to make sure I was getting the HDI dataset through from datasets.

**Comment by janezd** [comment]
What do you mean by "crash"? Do you get a pop-up window with some output? Can you share it?

I use often use HDI with geo coding and choropleth and it works, therefore we'd need more to understand what's going wrong on your machine.

**Comment by zokni41** [comment]
Hi Janez,

It's a straight freeze of the app. There's not much more I can monitor than the app completely freezes when I use the choropleth or geocoding widgets. I've provided screenshots of the freeze on the post. There's not really that much more to show.
I've used these plugins extensively and I've never ran into this problem until the latest update.

Best regards,

Charlie

On 6 Feb 2023 6:09 pm, Janez Demšar ***@***.***> wrote:

What do you mean by "crash"? Do you get a pop-up window with some output? Can you share it?

I use often use HDI with geo coding and choropleth and it works, therefore we'd need more to understand what's going wrong on your machine.

**Comment by janezd** [comment]
The latest release from a few days ago should have fixed this. Could you check, please?

**Comment by zokni41** [comment]
Hi Janez,

I confirm this has been fixed, thank you and the orange team for everything that you do!
Screenshot of it working with the HDI dataset from datasets
***@***.***

Best regards,

Charlie Watkinson
