### ISSUE TITLE
Geocoding - Encode forgets Identifier type

### ISSUE THREAD

**Issue by wvdvegte** [biolab/orange3-geo#179]
##### Geo version
0.4.2

##### Orange version
3.36.2

##### Expected behavior
When trying to encode coordinates for a city that is not a major city in Europe, a change in the setting for Identifier type is persistent when saving the ows file and opening it again

##### Actual behavior
Changed settings for Identifier type are changed back to Major city (Europe) when saving the ows file.
Geocoding appears to be one of the numerous widgets that doesn't keep their settings when saving the ows file.

##### Steps to reproduce the behavior
Open attached ows file, change the Identifier type to Major city (World), save the file and open it again.

##### Additional info (worksheets, data, screenshots, ...)
[Geocoding bug.ows.zip](https://github.com/biolab/orange3-geo/files/15076239/Geocoding.bug.ows.zip)

**Comment by janezd** [comment]
Thanks. I could easily reproduce it (thanks for instructions!). The error in the code is easy to see and annoying to fix. :)
