### ISSUE TITLE
geocoding fuction of geo widget stucked at 50%

### ISSUE THREAD

**Issue by vishal18021987** [biolab/orange3-geo#20]
sir/mam geocoding widget is not working when i am entering lattitude and longitude file it stucks at 50%. please provide a youtube video for it. which projection of lattitude /longitude we should take.

**Comment by kernc** [comment]
YouTube video is unnecessary. The widget should work as you expect it to. If it doesn't, it's a bug. Let it be the following bug:

Duplicate of https://github.com/biolab/orange3-geo/issues/21.
