### ISSUE TITLE
Installation issues; GeoCoding widget stuck at 50%

### ISSUE THREAD

**Issue by vishal18021987** [biolab/orange3-geo#21]
sir, i am installing geo widget in orange-3.4 but following packages needs to be installed externally then it was installed.

shutilwhich-1.1.0    python file

geos-0.2.1-py3-none-any.whl

pandas-0.17.1-cp34-none-win32.whl

Shapely-1.4.0-cp34-none-win32.whl

but after installation when i am loading any lat/long file in  of polygons in geocoding function of geo widget. it stucks at 50% and orange crashes.
please provide an youtube video to resolv this issue of loading files in geocoding function

**Comment by kernc** [comment]
1. `shutil.which()` should be [available in Python 3.4](https://docs.python.org/3/library/shutil.html#shutil.which).
2. pandas and Shapely are [listed in package dependencies](https://github.com/biolab/orange3-geo/blob/bdf0b891c28e5958e554988e433d9ba2f653f428/setup.py#L64-L71).
3. Shapely should install libGEOS as required.

Are you installing from git source or via PyPI?

**Comment by vishal18021987** [comment]
shutil.which() was not available in default orange installation.

Shapely is not installing libGEOS
 i have installed " Shapely-1.4.0-cp34-none-win32.whl "
and for geos i installed "geos-0.2.1-py3-none-any.whl  "

**Comment by kernc** [comment]
Are you installing Orange3-Geo from git source or via PyPI?

**Comment by kernc** [comment]
The "geos-0.2.1-py3-none-any.whl" package you installed is not the [libGEOS](https://trac.osgeo.org/geos/) needed by Shapely, so it's unlikely it has solved anything.

**Comment by vishal18021987** [comment]
now i installes CMAKE and i am installing libgeos then i will install shapely. is that you are saying....
will it work?

**Comment by kernc** [comment]
You don't need CMake unless you intend to compile libGEOS, no.

Instead:

Make sure you installed [Orange using the **Miniconda** installer](https://orange.biolab.si/download/). Running Orange, go to menu Options > Settings, tab Add-ons, and check "Install add-ons using conda" check box. Afterwards, Geo add-on should install without issues.

**Comment by jerneju** [comment]
I experience the same issue.

**Comment by ajdapretnar** [comment]
I haven't seen this with recent installations. However, I think #9 should fix most installation issues.
