### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-geo#25]
##### Geo version
`4693633c4c2c2a8aca723e980b15889ff72220d8` (current)

##### Orange version
`~3.8`

##### Expected behavior
Documentation should be shown.

##### Actual behavior
No documentation despite the fact that documentation file is in a repository.

##### Steps to reproduce the behavior
Open widget windows and press **F1**.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20171208_094428](https://user-images.githubusercontent.com/22157215/33757956-a7cc6c58-dbfc-11e7-8df2-8c2a2c3cda81.png)

**Comment by kernc** [comment]
When I do it, it works. Please try again. 😄

**Comment by jerneju** [comment]
Now it works.
