### ISSUE TITLE
Geo Map: color issue

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-geo#27]
##### Geo version
current (`>0.2.1`)

##### Orange version
current (`>3.8`)

##### Expected behavior
Widget can handle numeric variable colors which pass through black.

##### Actual behavior
Widget crashes.

>   File "orangecontrib/geo/widgets/owmap.py", line 240, in set_marker_color
>     if not np.isnan(min) else [])
>   File "orangecontrib/geo/widgets/owmap.py", line 239, in <listcomp>
>     [color_to_hex(i) for i in variable.colors if i]]
>   File "Orange/util.py", line 158, in color_to_hex
>     return "#{:02X}{:02X}{:02X}".format(*color)

##### Steps to reproduce the behavior
See the workflow below. Notice that numeric color's property **Pass through black** is selected.

**Geo Map** can show proper colors on a map but not in a legend.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20171212_094901](https://user-images.githubusercontent.com/22157215/33875389-692c5fc0-df22-11e7-8c48-9e0559567f1e.png)

![screenshot_20171212_095023](https://user-images.githubusercontent.com/22157215/33875642-2746e1a6-df23-11e7-89d3-79ff2613ca01.png)

**Comment by jerneju** [comment]
I would assign but I am unable to do so.

**Comment by jerneju** [comment]
https://sentry.io/biolab/orange3-geo/issues/416587398/

**Comment by kernc** [comment]
[Here the magic](https://github.com/biolab/orange3-geo/blob/dd7f510bf857a452b5834383be5b72af36458c37/orangecontrib/geo/widgets/_leaflet/owmap.js#L578-L583) happens wrt continuous colorspace in the legend. It's a simple CSS linear-gradient.
