### ISSUE TITLE
Choropleth Map: selected location shows wrong country

### ISSUE THREAD

**Issue by jerneju** [biolab/orange3-geo#31]
##### Geo version
Last version: `~0.1.8`

##### Orange version
`3.9dev`

##### Expected behavior
Coordinates should point to the correct country.

##### Actual behavior
Neighboring country is selected.

##### Steps to reproduce the behavior
_Illegal waste dumpsites in Slovenia (2017)_ is loaded in **Data Sets** widget and then point near the border is selected.

##### Additional info (worksheets, data, screenshots, ...)
![screenshot_20171222_102142](https://user-images.githubusercontent.com/22157215/34293066-844f3c8a-e703-11e7-9ade-589e0ac5f0b9.png)

**Comment by kernc** [comment]
Region shapes are simplified to save on file size. Not sure what there is to do about it.
![screenshot_2017-12-22_13-08-54](https://user-images.githubusercontent.com/684364/34297634-997ef40e-e719-11e7-9125-6397f0584453.png)

**Comment by ajdapretnar** [comment]
Probably a 'wontfix' (cantfix).
