### ISSUE TITLE
Qt version string parsing fails on Qt >= 5.10

### ISSUE THREAD

**Issue by djboris9** [biolab/orange3-geo#32]
##### Geo version
master and 0.2.1

##### Orange version
3.8

##### Expected behavior
Map widget will be loaded on Qt >= 5.10

##### Actual behavior
When starting Orange3 with Orange3-geo using log-level 4 on a installation with Qt >= 5.10 it fails to load the module with:
```
Error while importing 'Orange.widgets.visualize.owmap'.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 261, in iter_widget_descriptions
    module = asmodule(name)
  File "/usr/lib/python3.6/site-packages/Orange/canvas/registry/discovery.py", line 493, in asmodule
    return __import__(module, fromlist=[""])
  File "/usr/lib/python3.6/site-packages/Orange/widgets/visualize/owmap.py", line 26, in <module>
    raise RuntimeError('Map widget only works with Qt 5.3+')
RuntimeError: Map widget only works with Qt 5.3+
```

##### Steps to reproduce the behavior
Start Orange3 with Qt 5.10 or higher.

##### Additional info (worksheets, data, screenshots, ...)
In file `./orangecontrib/geo/widgets/owmap.py` there is a comparison error with the version string:
```
if QT_VERSION_STR <= '5.3':
raise RuntimeError('Map widget only works with Qt 5.3+')
```
Acutally my QT_VERSION_STR is "5.10.0", so this fails. After commenting this block out, the map starts to work again.

**Comment by kernc** [comment]
Thanks.
