### ISSUE TITLE
Choropleth shows wrong values for Mode aggregation

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-geo#33]
##### Geo version
0.2.2

##### Orange version
3.8

##### Expected behavior
Choropleth should use the same colors each time a visualization is shown

##### Steps to reproduce the behavior
1. Connect Illegal dump sites (from Datasets widget) to Choroplet.
2. Visualize Mode of Acess type. For me the colors are red, green and orange
![screen shot 2018-01-31 at 09 13 01](https://user-images.githubusercontent.com/588601/35611919-09ce3b7c-0667-11e8-8efd-76d7739b5eff.png)
3. Select Mode (or Acess type) again. Colors change.
![screen shot 2018-01-31 at 09 13 35](https://user-images.githubusercontent.com/588601/35611921-0ffafae4-0667-11e8-9070-8ca9a5beb9c0.png)

##### Additional info (worksheets, data, screenshots, ...)
![screen shot 2018-01-31 at 09 14 21](https://user-images.githubusercontent.com/588601/35611939-223bf924-0667-11e8-8d6d-21dcc12b3878.png)

**Comment by kernc** [comment]
This is by design. Notice Off-road is always red, On-foot always green, etc. These are `DiscreteVariable.colors`, per value, in order. Could have been set in Color widget for all we know, so can't just override that.

**Comment by astaric** [comment]
This is what I get when I first open the widget:

![screen shot 2018-01-31 at 12 36 02](https://user-images.githubusercontent.com/588601/35621063-5a904660-0683-11e8-9a8a-dd81b4af5dfe.png)

(I have included a boxplot to show the distribution of values for Karlovačka region. See that Private car is indeed the mode for the selected region)

When I re-select Access type, i get this:

![screen shot 2018-01-31 at 12 36 15](https://user-images.githubusercontent.com/588601/35621095-7c76d302-0683-11e8-92d8-f109c19b38e1.png)

Boxplot still shows the same distribution, so the color for the selected region should be orange, but it is drawn with green.
