### ISSUE TITLE
GeoCoding: suggested identifiers not found

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#37]
##### Geo version

0.2.3

##### Orange version

3.14.0

##### Expected behavior
GeoCoding can suggest appropriate alternatives to country names and takes them into consideration.

##### Actual behavior
When encoding North and South Korea, corresponding latitudes and longitudes are not found.

##### Steps to reproduce the behavior
Use HDI.txt (rename to .csv). Send to GeoCoding. Rename Korea (Democratic Republic of) to the suggested Dem. Rep. Korea. Latitude and longitude still not added.

##### Additional info (worksheets, data, screenshots, ...)
[HDI.txt](https://github.com/biolab/orange3-geo/files/2155218/HDI.txt)

<img width="1476" alt="screen shot 2018-07-02 at 14 48 51" src="https://user-images.githubusercontent.com/12524972/42164681-127a16fc-7e07-11e8-975b-beb35c660fda.png">

**Comment by robertcv** [comment]
This problem occurred due to missing geojson files. Please refer to the documentation.
