### ISSUE TITLE
Choropleth: if color by discrete, set aggregation to mode

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#39]
##### Geo version

0.2.3.

##### Orange version

3.15.dev

##### Expected behavior
Orange shows appropriate colors for discrete.

##### Actual behavior
The default would stay at Count, which would show nothing on HDI data (all blue).

##### Idea
If the color attribute is discrete, hide all that don't apply (mean, median, etc) and shift the default to mode.

##### Additional info (worksheets, data, screenshots, ...)
Use HDI data set from Data sets and perform clustering.

**Comment by janezd** [comment]
This is approximatelly fixed in #89: when switching from numeric to categorical variable, other options are removed and the default is select. Default, though, is count, not mode.

Are we OK with this or should we change the default to mode for categorical and mean for numeric? @ajdapretnar, @robertcv?

**Comment by robertcv** [comment]
When an aggregation attribute has changed the subset of functions is changed appropriately. If the current function is still applicable to the newly selected attribute then it stays the same, if not then it goes to its default (mode for discrete, count for other).

**Comment by ajdapretnar** [comment]
Yes, it is not bad as it is. IMO it would be a tad nicer to have Mode as default for categorical and Sum or Mean for numeric. But this is not major. The main point here was that non-applicable aggregations aren't shown, which they are not.
