### ISSUE TITLE
Geo Map: Topographic 2 requires API key

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#42]
##### Geo version

0.2.3

##### Orange version

3.16.dev

##### Issue
Choice of Topographic 2 map requires API key.

##### Steps to reproduce the behavior
File - Geo Map. Select Topographic 2.

##### Additional info (worksheets, data, screenshots, ...)
<img width="1049" alt="screen shot 2018-09-04 at 15 04 08" src="https://user-images.githubusercontent.com/12524972/45033107-d4935680-b053-11e8-92c7-1964075428ba.png">

**Comment by kernc** [comment]
Can replace https://github.com/biolab/orange3-geo/blob/0a421ce37b02ac265fec78e3df79172053655d8b/orangecontrib/geo/widgets/owmap.py#L627 with [`'OpenTopoMap'`](http://leaflet-extras.github.io/leaflet-providers/preview/index.html#filter=OpenTopoMap). Also check Topographic (1); all Thunderforest maps should be to register for.

**Comment by ajdapretnar** [comment]
Yup, it's the same for Topographic 1.

On a semi-related note: is the current OpenStreetMap too bright? I have a screenshot for before and it seems much better than the current version of OSM. Check Geo Map and see if you agree or not.

**Comment by kernc** [comment]
May have changed. Free to pick a better alternative: http://leaflet-extras.github.io/leaflet-providers/preview/index.html (Make sure it's free, fast, looks decent on all zoom levels.)
