### ISSUE TITLE
Geo Map: shorten drop downs

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#53]
##### Expected behavior
Combo box drop-downs are nice and cute.

##### Actual behavior
Drop-downs are super big (at least on OSX).

##### Steps to reproduce the behavior
Plot HDI in Geo Map.

##### Additional info (worksheets, data, screenshots, ...)
Image speaks for itself.

<img width="1305" alt="Screen Shot 2019-04-12 at 13 48 12" src="https://user-images.githubusercontent.com/12524972/56035204-cdd76b00-5d29-11e9-9076-7614839193f4.png">

**Comment by janezd** [comment]
We will change this to a searchable combo and limit the height (if we know how to).
