### ISSUE TITLE
Custom tooltip

### ISSUE THREAD

**Issue by bkmagnetron** [biolab/orange3-geo#57]
In Power BI there is an option to customize Tooltip, where it accepts a list of fields. Similar functionality in Orange3-geo will make it feel complete.
![image](https://user-images.githubusercontent.com/4893873/56532908-5220be00-6574-11e9-8219-7ad2e7dc4674.png)

**Comment by ajdapretnar** [comment]
I don't think this really belongs to Orange. Tooltips are just informative. If you wish to see the entire data, select the points of interest from the map and observe them in a Data Table.
We wish to refrain from putting everything but a kitchen sink into Orange to make it as easy to use as possible. Sure we are sacrificing some things for this, but we are willing to do this for the sake of simplicity.
I think this goes under wontfix. Sorry.

**Comment by bkmagnetron** [comment]
@ajdapretnar Thanks, though I'm new to Orange I haven't noticed the `Selected Data` output and the short to select is `Shift + LMB + Drag`. I can't able to find about this shortcut in the documentation, I only found it by trial and error.

**Comment by ajdapretnar** [comment]
This is written in the documentation:
> Note: To select a subset of points from the map, hold Shift and draw a rectangle around the point you want to output.

However, there used to be a message upon opening Geo Map for the first time with the information as well. I am not sure where it went, but surely it would make sense to (re-)implement it.
