### ISSUE TITLE
Geo Map: implement message regarding the selection of points

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#58]
##### Geo version

0.2.3

##### Orange version

3.20

##### Expected behavior
Geo Map provide information on how to select a subset of points.

##### Actual behavior
No information provided.

##### Additional info (worksheets, data, screenshots, ...)
We used to have messages upon opening widgets (for the first time, I suppose) that informed the user about selection. Where did they go?

**Comment by robertcv** [comment]
Cannot reproduce. The message pops up when I delete Orange setting.
