### ISSUE TITLE
GeoCoding: Better defaults for Latitude / Longitude 

### ISSUE THREAD

**Issue by astaric** [biolab/orange3-geo#6]
If a dataset does not have features that look like latitude/longitude (i.e. r"\b(lat|long)"), nothing should be selected in Latitude/Longitude.

**Comment by kernc** [comment]
The request is incompatible with current heuristic code, advised by @BlazZupan.
https://github.com/biolab/orange3-geo/blob/797088caf90e7403cd2ac25c752b14171984676f/orangecontrib/geo/utils.py#L27-L42

**Comment by ajdapretnar** [comment]
I agree we should have no attrs in GeoCoding if nothing matches. @BlazZupan Your thoughts?

**Comment by kernc** [comment]
Perhaps we could extend the heuristic to check if the points are also `not _all_between(values, -1, 1)` or similar. What case is breaking for you?

**Comment by robertcv** [comment]
![geocoding](https://user-images.githubusercontent.com/13180057/46660898-5a0ca800-cbb8-11e8-911f-56f921994959.png)
@astaric Is that what you hade in mind? I talked to @ajdapretnar and we think that it's not necessary anymore.

**Comment by ajdapretnar** [comment]
The current default is Encode, which switches to Decode only if no string or categorical attributes are present. When switching to Decode, lat/lon is the first attribute in the list. I think this makes sense. The use can always select a different attribute if he or she wants to.

**Comment by astaric** [comment]
Having encode as default option is good enough for my use-case.

Opening Philadelphia crime dataset now tries to encode Type instead of decoding Lan & Long by default, which might not be preferred. But since correct attributes are selected in Latitude an Longitude, having to switch from encoding to decoding might be good enough.

**Comment by ajdapretnar** [comment]
The idea is that Geocoding would _mostly_ be used for finding lat/lon pairs from region names. While it _can_ be used for Decoding, I assume it is rare.
For Philadelphia, for example, Decoding doesn't even work well, since even when selecting 2-level division, everything is still in Philadelphia, Pennsylvania. :D
