### ISSUE TITLE
Orange3 crashed when grag geomap 

### ISSUE THREAD

**Issue by ouening** [biolab/orange3-geo#67]
##### Actual behavior
crashed and orange3 quit automatically

##### Additional info (worksheets, data, screenshots, ...)

<pre>Error while importing &apos;orangecontrib.text.widgets.ownyt&apos;. The widget will not be shown.
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/dist-packages/orangecontrib/text/widgets/ownyt.py&quot;, line 16, in &lt;module&gt;
    from orangewidget import gui
ModuleNotFoundError: No module named &apos;orangewidget&apos;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/dist-packages/Orange/canvas/registry/discovery.py&quot;, line 257, in iter_widget_descriptions
    module = asmodule(name)
  File &quot;/usr/local/lib/python3.6/dist-packages/Orange/canvas/registry/discovery.py&quot;, line 484, in asmodule
    return __import__(module, fromlist=[&quot;&quot;])
  File &quot;/usr/local/lib/python3.6/dist-packages/orangecontrib/text/widgets/ownyt.py&quot;, line 18, in &lt;module&gt;
    from Orange.canvas.widgets.widget import gui
ModuleNotFoundError: No module named &apos;Orange.canvas.widgets&apos;
libpng warning: iCCP: known incorrect sRGB profile
/usr/local/lib/python3.6/dist-packages/Orange/widgets/utils/webview.py:97: UserWarning: To debug QWebEngineView, set environment variable QTWEBENGINE_REMOTE_DEBUGGING=12088 and then visit http://127.0.0.1:12088/ in a Chromium-based browser. See https://doc.qt.io/qt-5/qtwebengine-debugging.html This has also been done for you.
  &apos;This has also been done for you.&apos;.format(port=port))
[10611:10611:0706/142512.667143:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
</pre>

**Comment by ajdapretnar** [comment]
This you for reporting this, but this error is not the result of the GeoMap widget.
Probably GeoMap still crashes, because of the recent separation of Canvas and widgets.

https://github.com/biolab/orange3-geo/pull/66 will fix the issue (I think).
Also make sure you are on the latest master for all add-ons, since the errors will be fixed incrementally.

**Comment by ouening** [comment]
Still the error happens after I installed it from latest source.

<pre>FileNotFoundError: [Errno 2] No such file or directory: &apos;/home/gaoya/Applications/orange3-geo/orangecontrib/geo/geojson/admin0.json&apos;
Exception in thread Thread-1:
Traceback (most recent call last):
  File &quot;/usr/lib/python3.6/threading.py&quot;, line 916, in _bootstrap_inner
    self.run()
  File &quot;/usr/lib/python3.6/threading.py&quot;, line 864, in run
    self._target(*self._args, **self._kwargs)
  File &quot;/home/gaoya/Applications/orange3-geo/orangecontrib/geo/mapper.py&quot;, line 94, in init
    raise is_done_loading
RuntimeError: Missing GeoJSON files. In development environments, merge in the &quot;json&quot;branch. See CONTRIBUTING.md

Error while importing &apos;orangecontrib.text.widgets.ownyt&apos;. The widget will not be shown.
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/dist-packages/orangecontrib/text/widgets/ownyt.py&quot;, line 16, in &lt;module&gt;
    from orangewidget import gui
ModuleNotFoundError: No module named &apos;orangewidget&apos;

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.6/dist-packages/Orange/canvas/registry/discovery.py&quot;, line 257, in iter_widget_descriptions
    module = asmodule(name)
  File &quot;/usr/local/lib/python3.6/dist-packages/Orange/canvas/registry/discovery.py&quot;, line 484, in asmodule
    return __import__(module, fromlist=[&quot;&quot;])
  File &quot;/usr/local/lib/python3.6/dist-packages/orangecontrib/text/widgets/ownyt.py&quot;, line 18, in &lt;module&gt;
    from Orange.canvas.widgets.widget import gui
ModuleNotFoundError: No module named &apos;Orange.canvas.widgets&apos;
libpng warning: iCCP: known incorrect sRGB profile
/usr/local/lib/python3.6/dist-packages/Orange/widgets/utils/webview.py:97: UserWarning: To debug QWebEngineView, set environment variable QTWEBENGINE_REMOTE_DEBUGGING=12088 and then visit http://127.0.0.1:12088/ in a Chromium-based browser. See https://doc.qt.io/qt-5/qtwebengine-debugging.html This has also been done for you.
  &apos;This has also been done for you.&apos;.format(port=port))
[15131:15131:0709/101656.575681:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Received signal 11 SEGV_MAPERR 000000000008
#0 0x7f42ee5788bf &lt;unknown&gt;
#1 0x7f42ee578cbb &lt;unknown&gt;
#2 0x7f42ee57933e &lt;unknown&gt;
#3 0x7f4343f73f20 &lt;unknown&gt;
#4 0x7f42eae1dc64 QVector&lt;&gt;::resize()
#5 0x7f42eae1bf09 QSslSocketBackendPrivate::startHandshake()
#6 0x7f42eae1cc34 QSslSocketBackendPrivate::transmit()
#7 0x7f42eadfe091 QSslSocket::qt_static_metacall()
#8 0x7f4337a39989 QMetaObject::activate()
#9 0x7f42eadc9ce3 QAbstractSocketPrivate::emitReadyRead()
#10 0x7f42eadc9d9c QAbstractSocketPrivate::canReadNotification()
#11 0x7f42eaddc101 QReadNotifier::event()
#12 0x7f4310f6d6fc QApplicationPrivate::notify_helper()
#13 0x7f4310f747f0 QApplication::notify()
#14 0x7f4313f47f5e sipQApplication::notify()
#15 0x7f4337a0de98 QCoreApplication::notifyInternal2()
#16 0x7f4337a65f08 socketNotifierSourceDispatch()
#17 0x7f4334a60317 g_main_context_dispatch
#18 0x7f4334a60550 &lt;unknown&gt;
#19 0x7f4334a605dc g_main_context_iteration
#20 0x7f4337a652eb QEventDispatcherGlib::processEvents()
#21 0x7f4337a0c7fa QEventLoop::exec()
#22 0x7f433783f87c QThread::exec()
#23 0x7f4337840db3 QThreadPrivate::start()
#24 0x7f4343d1d6db start_thread
#25 0x7f434405688f clone
  r8: 00007f422c00a1c0  r9: 00007f422c008030 r10: 00007f424e622c40 r11: 0000000000000003
 r12: 00000000037c6980 r13: 0000000000000000 r14: 00007f422c009600 r15: 00007f424e622930
  di: 0000000000000008  si: 0000000000000000  bp: 0000000000000001  bx: 0000000000000000
  dx: 0000000000000000  ax: 00000000fffffffe  cx: 00007f422c008540  sp: 00007f424e621740
  ip: 00007f42eae1dc64 efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 0000000000000008
[end of stack trace]
Calling _exit(1). Core file will not be generated.
</pre>

**Comment by ajdapretnar** [comment]
Yes, because #66 is not yet merged. Once it will be, the problem will be fixed. You also need to update your Text add-on to the latest master. And follow instructions in https://github.com/biolab/orange3-geo/blob/master/CONTRIBUTING.md to retrieve the GeoJSON files.
