### ISSUE TITLE
Cannot install this add on

### ISSUE THREAD

**Issue by slbarron2323** [biolab/orange3-geo#82]
##### Geo version
0.2.4.post1

##### Orange version
3.23.1

##### Expected behavior
installs the geo add on

##### Actual behavior
error message

An error occured while running a subprocess
Comand failed: python python-m pip install --constraint (location of file) exited with non zero status

**Comment by markotoplak** [comment]
Thanks for the report. How did you try to install that add-on? Could you also show the output (what caused the non-zero status?

**Comment by robertcv** [comment]
@slbarron2323 Go to Options -> Settings -> Add-ons and check "install add-ons with conda" and then retry installing the add-on.

**Comment by slbarron23** [comment]
Sorted thank you!
