### ISSUE TITLE
GeoMap - Cannot fetch map from the internet

### ISSUE THREAD

**Issue by JulianDEcheverry** [biolab/orange3-geo#84]
##### Geo version

0.2.5

##### Orange version

3.22

##### Expected behavior
When double click on GeoMap, the map is shown in the background

##### Actual behavior
Map does not appear and there is a warning message in the bottom of the GeoMap window "Cannot fetch map from the internet. Displaying only cached parts"

##### Steps to reproduce the behavior
When dropping the GeoMap widget on the workspace, there is a warning sign in the top of the widget icon. Then, by double-clicking it, there is a warning message and no map displayed.

##### Additional info (worksheets, data, screenshots, ...)
![image](https://user-images.githubusercontent.com/42276173/69767999-c47e0000-114c-11ea-971e-425c901bb805.png)

**Comment by robertcv** [comment]
Hey! This widget requires a (good) internet connection to load maps. Are you connected, perhaps is your connection restricted, do you use a proxy? Try if it works on a different connection.

**Comment by JulianDEcheverry** [comment]
Hi Robert. I have tried many things and I think the connection is not the problem. Actually, I've even tried in different computers (MAC, windows) and in different locations (university, my place) and the result is the same. A funny thing -> I see the map when clicking the link in the help window of the GeoMap widget. But cannot see it from the GeoMap widget directly.
<img width="621" alt="Screenshot01" src="https://user-images.githubusercontent.com/42276173/69812015-60475480-11bd-11ea-870a-50b37ce9ce33.png">
<img width="578" alt="Screenshot02" src="https://user-images.githubusercontent.com/42276173/69812016-60dfeb00-11bd-11ea-8264-46d07277af9e.png">

**Comment by ajdapretnar** [comment]
That _is_ strange. How did you install the add-on?

**Comment by ajdapretnar** [comment]
@robertcv I can reproduce on my computer. We can check tomorrow and figure out why this happens.

**Comment by JulianDEcheverry** [comment]
I installed it by:
Options -> Add-ons -> Orange3-Geo (v. 0.25) (Checked) -> Install
