### ISSUE TITLE
GeoMap: find lat/lon

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#92]
Upon every domain change, try to find lat/lon values. This is especially useful when Geocoding is added. Currently, GeoMap doesn't find these values, when being fed the data from Geocoding.

The lat/lon should not be changed if the user manually set the values before.

Also, latitude should come before longitude. At least this seems to be the convention.

**Comment by ajdapretnar** [comment]
One more thing. Class values and metas should be organized the way they are organized in the Scatter Plot widget.

**Comment by robertcv** [comment]
About the lat before lon: for visualizing I thought it was better to change the order because lon represents the X-axis and lat represents the Y-axis.

**Comment by ajdapretnar** [comment]
I don't know if the user's thinking goes that deep. It is most common to see latitude before longitude and this is the way it was before. Up for discussion of course.

**Comment by ajdapretnar** [comment]
Even with recent changes, the values are not updated. Probably because of context settings.

Also, I am again arguing for lat/lon order. It *is* the convention.
https://stackoverflow.com/questions/7309121/preferred-order-of-writing-latitude-longitude-tuples

**Comment by robertcv** [comment]
The first problem is redundant with #40 the second one is solved by #102.
