### ISSUE TITLE
GeoMap: update on feature change

### ISSUE THREAD

**Issue by ajdapretnar** [biolab/orange3-geo#95]
##### Geo version

0.2.6

##### Orange version

3.25.dev

##### Expected behavior
Geo Map changes plot when attribute changes.

##### Actual behavior
Nothing changes, dots remain the same.

##### Steps to reproduce the behavior
Data - GeoMap, change attribute.

**Comment by robertcv** [comment]
Cannot reproduce. Could you please provide more information. What data did you use, what attributes did you change?

**Comment by ajdapretnar** [comment]
Yes, I can't reproduce it anymore either.
